// Copyright (c) 2017-2021 Uber Technologies Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Code generated by thriftrw v1.11.0. DO NOT EDIT.
// @generated

package shadower

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go.uber.org/cadence/.gen/go/shared"
	"go.uber.org/thriftrw/wire"
	"math"
	"strconv"
	"strings"
)

type ExitCondition struct {
	ExpirationIntervalInSeconds *int32 `json:"expirationIntervalInSeconds,omitempty"`
	ShadowCount                 *int32 `json:"shadowCount,omitempty"`
}

// ToWire translates a ExitCondition struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *ExitCondition) ToWire() (wire.Value, error) {
	var (
		fields [2]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.ExpirationIntervalInSeconds != nil {
		w, err = wire.NewValueI32(*(v.ExpirationIntervalInSeconds)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 10, Value: w}
		i++
	}
	if v.ShadowCount != nil {
		w, err = wire.NewValueI32(*(v.ShadowCount)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 20, Value: w}
		i++
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

// FromWire deserializes a ExitCondition struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a ExitCondition struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v ExitCondition
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *ExitCondition) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 10:
			if field.Value.Type() == wire.TI32 {
				var x int32
				x, err = field.Value.GetI32(), error(nil)
				v.ExpirationIntervalInSeconds = &x
				if err != nil {
					return err
				}

			}
		case 20:
			if field.Value.Type() == wire.TI32 {
				var x int32
				x, err = field.Value.GetI32(), error(nil)
				v.ShadowCount = &x
				if err != nil {
					return err
				}

			}
		}
	}

	return nil
}

// String returns a readable string representation of a ExitCondition
// struct.
func (v *ExitCondition) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [2]string
	i := 0
	if v.ExpirationIntervalInSeconds != nil {
		fields[i] = fmt.Sprintf("ExpirationIntervalInSeconds: %v", *(v.ExpirationIntervalInSeconds))
		i++
	}
	if v.ShadowCount != nil {
		fields[i] = fmt.Sprintf("ShadowCount: %v", *(v.ShadowCount))
		i++
	}

	return fmt.Sprintf("ExitCondition{%v}", strings.Join(fields[:i], ", "))
}

func _I32_EqualsPtr(lhs, rhs *int32) bool {
	if lhs != nil && rhs != nil {

		x := *lhs
		y := *rhs
		return (x == y)
	}
	return lhs == nil && rhs == nil
}

// Equals returns true if all the fields of this ExitCondition match the
// provided ExitCondition.
//
// This function performs a deep comparison.
func (v *ExitCondition) Equals(rhs *ExitCondition) bool {
	if !_I32_EqualsPtr(v.ExpirationIntervalInSeconds, rhs.ExpirationIntervalInSeconds) {
		return false
	}
	if !_I32_EqualsPtr(v.ShadowCount, rhs.ShadowCount) {
		return false
	}

	return true
}

// GetExpirationIntervalInSeconds returns the value of ExpirationIntervalInSeconds if it is set or its
// zero value if it is unset.
func (v *ExitCondition) GetExpirationIntervalInSeconds() (o int32) {
	if v.ExpirationIntervalInSeconds != nil {
		return *v.ExpirationIntervalInSeconds
	}

	return
}

// GetShadowCount returns the value of ShadowCount if it is set or its
// zero value if it is unset.
func (v *ExitCondition) GetShadowCount() (o int32) {
	if v.ShadowCount != nil {
		return *v.ShadowCount
	}

	return
}

type Mode int32

const (
	ModeNormal     Mode = 0
	ModeContinuous Mode = 1
)

// Mode_Values returns all recognized values of Mode.
func Mode_Values() []Mode {
	return []Mode{
		ModeNormal,
		ModeContinuous,
	}
}

// UnmarshalText tries to decode Mode from a byte slice
// containing its name.
//
//   var v Mode
//   err := v.UnmarshalText([]byte("Normal"))
func (v *Mode) UnmarshalText(value []byte) error {
	switch string(value) {
	case "Normal":
		*v = ModeNormal
		return nil
	case "Continuous":
		*v = ModeContinuous
		return nil
	default:
		return fmt.Errorf("unknown enum value %q for %q", value, "Mode")
	}
}

// Ptr returns a pointer to this enum value.
func (v Mode) Ptr() *Mode {
	return &v
}

// ToWire translates Mode into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// Enums are represented as 32-bit integers over the wire.
func (v Mode) ToWire() (wire.Value, error) {
	return wire.NewValueI32(int32(v)), nil
}

// FromWire deserializes Mode from its Thrift-level
// representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TI32)
//   if err != nil {
//     return Mode(0), err
//   }
//
//   var v Mode
//   if err := v.FromWire(x); err != nil {
//     return Mode(0), err
//   }
//   return v, nil
func (v *Mode) FromWire(w wire.Value) error {
	*v = (Mode)(w.GetI32())
	return nil
}

// String returns a readable string representation of Mode.
func (v Mode) String() string {
	w := int32(v)
	switch w {
	case 0:
		return "Normal"
	case 1:
		return "Continuous"
	}
	return fmt.Sprintf("Mode(%d)", w)
}

// Equals returns true if this Mode value matches the provided
// value.
func (v Mode) Equals(rhs Mode) bool {
	return v == rhs
}

// MarshalJSON serializes Mode into JSON.
//
// If the enum value is recognized, its name is returned. Otherwise,
// its integer value is returned.
//
// This implements json.Marshaler.
func (v Mode) MarshalJSON() ([]byte, error) {
	switch int32(v) {
	case 0:
		return ([]byte)("\"Normal\""), nil
	case 1:
		return ([]byte)("\"Continuous\""), nil
	}
	return ([]byte)(strconv.FormatInt(int64(v), 10)), nil
}

// UnmarshalJSON attempts to decode Mode from its JSON
// representation.
//
// This implementation supports both, numeric and string inputs. If a
// string is provided, it must be a known enum name.
//
// This implements json.Unmarshaler.
func (v *Mode) UnmarshalJSON(text []byte) error {
	d := json.NewDecoder(bytes.NewReader(text))
	d.UseNumber()
	t, err := d.Token()
	if err != nil {
		return err
	}

	switch w := t.(type) {
	case json.Number:
		x, err := w.Int64()
		if err != nil {
			return err
		}
		if x > math.MaxInt32 {
			return fmt.Errorf("enum overflow from JSON %q for %q", text, "Mode")
		}
		if x < math.MinInt32 {
			return fmt.Errorf("enum underflow from JSON %q for %q", text, "Mode")
		}
		*v = (Mode)(x)
		return nil
	case string:
		return v.UnmarshalText([]byte(w))
	default:
		return fmt.Errorf("invalid JSON value %q (%T) to unmarshal into %q", t, t, "Mode")
	}
}

type ReplayWorkflowActivityParams struct {
	Domain     *string                     `json:"domain,omitempty"`
	Executions []*shared.WorkflowExecution `json:"executions,omitempty"`
}

type _List_WorkflowExecution_ValueList []*shared.WorkflowExecution

func (v _List_WorkflowExecution_ValueList) ForEach(f func(wire.Value) error) error {
	for i, x := range v {
		if x == nil {
			return fmt.Errorf("invalid [%v]: value is nil", i)
		}
		w, err := x.ToWire()
		if err != nil {
			return err
		}
		err = f(w)
		if err != nil {
			return err
		}
	}
	return nil
}

func (v _List_WorkflowExecution_ValueList) Size() int {
	return len(v)
}

func (_List_WorkflowExecution_ValueList) ValueType() wire.Type {
	return wire.TStruct
}

func (_List_WorkflowExecution_ValueList) Close() {}

// ToWire translates a ReplayWorkflowActivityParams struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *ReplayWorkflowActivityParams) ToWire() (wire.Value, error) {
	var (
		fields [2]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.Domain != nil {
		w, err = wire.NewValueString(*(v.Domain)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 10, Value: w}
		i++
	}
	if v.Executions != nil {
		w, err = wire.NewValueList(_List_WorkflowExecution_ValueList(v.Executions)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 20, Value: w}
		i++
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func _WorkflowExecution_Read(w wire.Value) (*shared.WorkflowExecution, error) {
	var v shared.WorkflowExecution
	err := v.FromWire(w)
	return &v, err
}

func _List_WorkflowExecution_Read(l wire.ValueList) ([]*shared.WorkflowExecution, error) {
	if l.ValueType() != wire.TStruct {
		return nil, nil
	}

	o := make([]*shared.WorkflowExecution, 0, l.Size())
	err := l.ForEach(func(x wire.Value) error {
		i, err := _WorkflowExecution_Read(x)
		if err != nil {
			return err
		}
		o = append(o, i)
		return nil
	})
	l.Close()
	return o, err
}

// FromWire deserializes a ReplayWorkflowActivityParams struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a ReplayWorkflowActivityParams struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v ReplayWorkflowActivityParams
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *ReplayWorkflowActivityParams) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 10:
			if field.Value.Type() == wire.TBinary {
				var x string
				x, err = field.Value.GetString(), error(nil)
				v.Domain = &x
				if err != nil {
					return err
				}

			}
		case 20:
			if field.Value.Type() == wire.TList {
				v.Executions, err = _List_WorkflowExecution_Read(field.Value.GetList())
				if err != nil {
					return err
				}

			}
		}
	}

	return nil
}

// String returns a readable string representation of a ReplayWorkflowActivityParams
// struct.
func (v *ReplayWorkflowActivityParams) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [2]string
	i := 0
	if v.Domain != nil {
		fields[i] = fmt.Sprintf("Domain: %v", *(v.Domain))
		i++
	}
	if v.Executions != nil {
		fields[i] = fmt.Sprintf("Executions: %v", v.Executions)
		i++
	}

	return fmt.Sprintf("ReplayWorkflowActivityParams{%v}", strings.Join(fields[:i], ", "))
}

func _String_EqualsPtr(lhs, rhs *string) bool {
	if lhs != nil && rhs != nil {

		x := *lhs
		y := *rhs
		return (x == y)
	}
	return lhs == nil && rhs == nil
}

func _List_WorkflowExecution_Equals(lhs, rhs []*shared.WorkflowExecution) bool {
	if len(lhs) != len(rhs) {
		return false
	}

	for i, lv := range lhs {
		rv := rhs[i]
		if !lv.Equals(rv) {
			return false
		}
	}

	return true
}

// Equals returns true if all the fields of this ReplayWorkflowActivityParams match the
// provided ReplayWorkflowActivityParams.
//
// This function performs a deep comparison.
func (v *ReplayWorkflowActivityParams) Equals(rhs *ReplayWorkflowActivityParams) bool {
	if !_String_EqualsPtr(v.Domain, rhs.Domain) {
		return false
	}
	if !((v.Executions == nil && rhs.Executions == nil) || (v.Executions != nil && rhs.Executions != nil && _List_WorkflowExecution_Equals(v.Executions, rhs.Executions))) {
		return false
	}

	return true
}

// GetDomain returns the value of Domain if it is set or its
// zero value if it is unset.
func (v *ReplayWorkflowActivityParams) GetDomain() (o string) {
	if v.Domain != nil {
		return *v.Domain
	}

	return
}

type ReplayWorkflowActivityResult struct {
	Succeeded *int32 `json:"succeeded,omitempty"`
	Skipped   *int32 `json:"skipped,omitempty"`
	Failed    *int32 `json:"failed,omitempty"`
}

// ToWire translates a ReplayWorkflowActivityResult struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *ReplayWorkflowActivityResult) ToWire() (wire.Value, error) {
	var (
		fields [3]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.Succeeded != nil {
		w, err = wire.NewValueI32(*(v.Succeeded)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 10, Value: w}
		i++
	}
	if v.Skipped != nil {
		w, err = wire.NewValueI32(*(v.Skipped)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 20, Value: w}
		i++
	}
	if v.Failed != nil {
		w, err = wire.NewValueI32(*(v.Failed)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 30, Value: w}
		i++
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

// FromWire deserializes a ReplayWorkflowActivityResult struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a ReplayWorkflowActivityResult struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v ReplayWorkflowActivityResult
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *ReplayWorkflowActivityResult) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 10:
			if field.Value.Type() == wire.TI32 {
				var x int32
				x, err = field.Value.GetI32(), error(nil)
				v.Succeeded = &x
				if err != nil {
					return err
				}

			}
		case 20:
			if field.Value.Type() == wire.TI32 {
				var x int32
				x, err = field.Value.GetI32(), error(nil)
				v.Skipped = &x
				if err != nil {
					return err
				}

			}
		case 30:
			if field.Value.Type() == wire.TI32 {
				var x int32
				x, err = field.Value.GetI32(), error(nil)
				v.Failed = &x
				if err != nil {
					return err
				}

			}
		}
	}

	return nil
}

// String returns a readable string representation of a ReplayWorkflowActivityResult
// struct.
func (v *ReplayWorkflowActivityResult) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [3]string
	i := 0
	if v.Succeeded != nil {
		fields[i] = fmt.Sprintf("Succeeded: %v", *(v.Succeeded))
		i++
	}
	if v.Skipped != nil {
		fields[i] = fmt.Sprintf("Skipped: %v", *(v.Skipped))
		i++
	}
	if v.Failed != nil {
		fields[i] = fmt.Sprintf("Failed: %v", *(v.Failed))
		i++
	}

	return fmt.Sprintf("ReplayWorkflowActivityResult{%v}", strings.Join(fields[:i], ", "))
}

// Equals returns true if all the fields of this ReplayWorkflowActivityResult match the
// provided ReplayWorkflowActivityResult.
//
// This function performs a deep comparison.
func (v *ReplayWorkflowActivityResult) Equals(rhs *ReplayWorkflowActivityResult) bool {
	if !_I32_EqualsPtr(v.Succeeded, rhs.Succeeded) {
		return false
	}
	if !_I32_EqualsPtr(v.Skipped, rhs.Skipped) {
		return false
	}
	if !_I32_EqualsPtr(v.Failed, rhs.Failed) {
		return false
	}

	return true
}

// GetSucceeded returns the value of Succeeded if it is set or its
// zero value if it is unset.
func (v *ReplayWorkflowActivityResult) GetSucceeded() (o int32) {
	if v.Succeeded != nil {
		return *v.Succeeded
	}

	return
}

// GetSkipped returns the value of Skipped if it is set or its
// zero value if it is unset.
func (v *ReplayWorkflowActivityResult) GetSkipped() (o int32) {
	if v.Skipped != nil {
		return *v.Skipped
	}

	return
}

// GetFailed returns the value of Failed if it is set or its
// zero value if it is unset.
func (v *ReplayWorkflowActivityResult) GetFailed() (o int32) {
	if v.Failed != nil {
		return *v.Failed
	}

	return
}

type ScanWorkflowActivityParams struct {
	Domain        *string  `json:"domain,omitempty"`
	WorkflowQuery *string  `json:"workflowQuery,omitempty"`
	NextPageToken []byte   `json:"nextPageToken,omitempty"`
	PageSize      *int32   `json:"pageSize,omitempty"`
	SamplingRate  *float64 `json:"samplingRate,omitempty"`
}

// ToWire translates a ScanWorkflowActivityParams struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *ScanWorkflowActivityParams) ToWire() (wire.Value, error) {
	var (
		fields [5]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.Domain != nil {
		w, err = wire.NewValueString(*(v.Domain)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 10, Value: w}
		i++
	}
	if v.WorkflowQuery != nil {
		w, err = wire.NewValueString(*(v.WorkflowQuery)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 20, Value: w}
		i++
	}
	if v.NextPageToken != nil {
		w, err = wire.NewValueBinary(v.NextPageToken), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 30, Value: w}
		i++
	}
	if v.PageSize != nil {
		w, err = wire.NewValueI32(*(v.PageSize)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 40, Value: w}
		i++
	}
	if v.SamplingRate != nil {
		w, err = wire.NewValueDouble(*(v.SamplingRate)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 50, Value: w}
		i++
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

// FromWire deserializes a ScanWorkflowActivityParams struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a ScanWorkflowActivityParams struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v ScanWorkflowActivityParams
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *ScanWorkflowActivityParams) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 10:
			if field.Value.Type() == wire.TBinary {
				var x string
				x, err = field.Value.GetString(), error(nil)
				v.Domain = &x
				if err != nil {
					return err
				}

			}
		case 20:
			if field.Value.Type() == wire.TBinary {
				var x string
				x, err = field.Value.GetString(), error(nil)
				v.WorkflowQuery = &x
				if err != nil {
					return err
				}

			}
		case 30:
			if field.Value.Type() == wire.TBinary {
				v.NextPageToken, err = field.Value.GetBinary(), error(nil)
				if err != nil {
					return err
				}

			}
		case 40:
			if field.Value.Type() == wire.TI32 {
				var x int32
				x, err = field.Value.GetI32(), error(nil)
				v.PageSize = &x
				if err != nil {
					return err
				}

			}
		case 50:
			if field.Value.Type() == wire.TDouble {
				var x float64
				x, err = field.Value.GetDouble(), error(nil)
				v.SamplingRate = &x
				if err != nil {
					return err
				}

			}
		}
	}

	return nil
}

// String returns a readable string representation of a ScanWorkflowActivityParams
// struct.
func (v *ScanWorkflowActivityParams) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [5]string
	i := 0
	if v.Domain != nil {
		fields[i] = fmt.Sprintf("Domain: %v", *(v.Domain))
		i++
	}
	if v.WorkflowQuery != nil {
		fields[i] = fmt.Sprintf("WorkflowQuery: %v", *(v.WorkflowQuery))
		i++
	}
	if v.NextPageToken != nil {
		fields[i] = fmt.Sprintf("NextPageToken: %v", v.NextPageToken)
		i++
	}
	if v.PageSize != nil {
		fields[i] = fmt.Sprintf("PageSize: %v", *(v.PageSize))
		i++
	}
	if v.SamplingRate != nil {
		fields[i] = fmt.Sprintf("SamplingRate: %v", *(v.SamplingRate))
		i++
	}

	return fmt.Sprintf("ScanWorkflowActivityParams{%v}", strings.Join(fields[:i], ", "))
}

func _Double_EqualsPtr(lhs, rhs *float64) bool {
	if lhs != nil && rhs != nil {

		x := *lhs
		y := *rhs
		return (x == y)
	}
	return lhs == nil && rhs == nil
}

// Equals returns true if all the fields of this ScanWorkflowActivityParams match the
// provided ScanWorkflowActivityParams.
//
// This function performs a deep comparison.
func (v *ScanWorkflowActivityParams) Equals(rhs *ScanWorkflowActivityParams) bool {
	if !_String_EqualsPtr(v.Domain, rhs.Domain) {
		return false
	}
	if !_String_EqualsPtr(v.WorkflowQuery, rhs.WorkflowQuery) {
		return false
	}
	if !((v.NextPageToken == nil && rhs.NextPageToken == nil) || (v.NextPageToken != nil && rhs.NextPageToken != nil && bytes.Equal(v.NextPageToken, rhs.NextPageToken))) {
		return false
	}
	if !_I32_EqualsPtr(v.PageSize, rhs.PageSize) {
		return false
	}
	if !_Double_EqualsPtr(v.SamplingRate, rhs.SamplingRate) {
		return false
	}

	return true
}

// GetDomain returns the value of Domain if it is set or its
// zero value if it is unset.
func (v *ScanWorkflowActivityParams) GetDomain() (o string) {
	if v.Domain != nil {
		return *v.Domain
	}

	return
}

// GetWorkflowQuery returns the value of WorkflowQuery if it is set or its
// zero value if it is unset.
func (v *ScanWorkflowActivityParams) GetWorkflowQuery() (o string) {
	if v.WorkflowQuery != nil {
		return *v.WorkflowQuery
	}

	return
}

// GetPageSize returns the value of PageSize if it is set or its
// zero value if it is unset.
func (v *ScanWorkflowActivityParams) GetPageSize() (o int32) {
	if v.PageSize != nil {
		return *v.PageSize
	}

	return
}

// GetSamplingRate returns the value of SamplingRate if it is set or its
// zero value if it is unset.
func (v *ScanWorkflowActivityParams) GetSamplingRate() (o float64) {
	if v.SamplingRate != nil {
		return *v.SamplingRate
	}

	return
}

type ScanWorkflowActivityResult struct {
	Executions    []*shared.WorkflowExecution `json:"executions,omitempty"`
	NextPageToken []byte                      `json:"nextPageToken,omitempty"`
}

// ToWire translates a ScanWorkflowActivityResult struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *ScanWorkflowActivityResult) ToWire() (wire.Value, error) {
	var (
		fields [2]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.Executions != nil {
		w, err = wire.NewValueList(_List_WorkflowExecution_ValueList(v.Executions)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 10, Value: w}
		i++
	}
	if v.NextPageToken != nil {
		w, err = wire.NewValueBinary(v.NextPageToken), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 20, Value: w}
		i++
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

// FromWire deserializes a ScanWorkflowActivityResult struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a ScanWorkflowActivityResult struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v ScanWorkflowActivityResult
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *ScanWorkflowActivityResult) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 10:
			if field.Value.Type() == wire.TList {
				v.Executions, err = _List_WorkflowExecution_Read(field.Value.GetList())
				if err != nil {
					return err
				}

			}
		case 20:
			if field.Value.Type() == wire.TBinary {
				v.NextPageToken, err = field.Value.GetBinary(), error(nil)
				if err != nil {
					return err
				}

			}
		}
	}

	return nil
}

// String returns a readable string representation of a ScanWorkflowActivityResult
// struct.
func (v *ScanWorkflowActivityResult) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [2]string
	i := 0
	if v.Executions != nil {
		fields[i] = fmt.Sprintf("Executions: %v", v.Executions)
		i++
	}
	if v.NextPageToken != nil {
		fields[i] = fmt.Sprintf("NextPageToken: %v", v.NextPageToken)
		i++
	}

	return fmt.Sprintf("ScanWorkflowActivityResult{%v}", strings.Join(fields[:i], ", "))
}

// Equals returns true if all the fields of this ScanWorkflowActivityResult match the
// provided ScanWorkflowActivityResult.
//
// This function performs a deep comparison.
func (v *ScanWorkflowActivityResult) Equals(rhs *ScanWorkflowActivityResult) bool {
	if !((v.Executions == nil && rhs.Executions == nil) || (v.Executions != nil && rhs.Executions != nil && _List_WorkflowExecution_Equals(v.Executions, rhs.Executions))) {
		return false
	}
	if !((v.NextPageToken == nil && rhs.NextPageToken == nil) || (v.NextPageToken != nil && rhs.NextPageToken != nil && bytes.Equal(v.NextPageToken, rhs.NextPageToken))) {
		return false
	}

	return true
}

type WorkflowParams struct {
	Domain        *string         `json:"domain,omitempty"`
	TaskList      *string         `json:"taskList,omitempty"`
	WorkflowQuery *string         `json:"workflowQuery,omitempty"`
	NextPageToken []byte          `json:"nextPageToken,omitempty"`
	SamplingRate  *float64        `json:"samplingRate,omitempty"`
	ShadowMode    *Mode           `json:"shadowMode,omitempty"`
	ExitCondition *ExitCondition  `json:"exitCondition,omitempty"`
	Concurrency   *int32          `json:"concurrency,omitempty"`
	LastRunResult *WorkflowResult `json:"lastRunResult,omitempty"`
}

// ToWire translates a WorkflowParams struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *WorkflowParams) ToWire() (wire.Value, error) {
	var (
		fields [9]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.Domain != nil {
		w, err = wire.NewValueString(*(v.Domain)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 10, Value: w}
		i++
	}
	if v.TaskList != nil {
		w, err = wire.NewValueString(*(v.TaskList)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 20, Value: w}
		i++
	}
	if v.WorkflowQuery != nil {
		w, err = wire.NewValueString(*(v.WorkflowQuery)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 30, Value: w}
		i++
	}
	if v.NextPageToken != nil {
		w, err = wire.NewValueBinary(v.NextPageToken), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 40, Value: w}
		i++
	}
	if v.SamplingRate != nil {
		w, err = wire.NewValueDouble(*(v.SamplingRate)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 50, Value: w}
		i++
	}
	if v.ShadowMode != nil {
		w, err = v.ShadowMode.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 60, Value: w}
		i++
	}
	if v.ExitCondition != nil {
		w, err = v.ExitCondition.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 70, Value: w}
		i++
	}
	if v.Concurrency != nil {
		w, err = wire.NewValueI32(*(v.Concurrency)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 80, Value: w}
		i++
	}
	if v.LastRunResult != nil {
		w, err = v.LastRunResult.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 90, Value: w}
		i++
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func _Mode_Read(w wire.Value) (Mode, error) {
	var v Mode
	err := v.FromWire(w)
	return v, err
}

func _ExitCondition_Read(w wire.Value) (*ExitCondition, error) {
	var v ExitCondition
	err := v.FromWire(w)
	return &v, err
}

func _WorkflowResult_Read(w wire.Value) (*WorkflowResult, error) {
	var v WorkflowResult
	err := v.FromWire(w)
	return &v, err
}

// FromWire deserializes a WorkflowParams struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a WorkflowParams struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v WorkflowParams
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *WorkflowParams) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 10:
			if field.Value.Type() == wire.TBinary {
				var x string
				x, err = field.Value.GetString(), error(nil)
				v.Domain = &x
				if err != nil {
					return err
				}

			}
		case 20:
			if field.Value.Type() == wire.TBinary {
				var x string
				x, err = field.Value.GetString(), error(nil)
				v.TaskList = &x
				if err != nil {
					return err
				}

			}
		case 30:
			if field.Value.Type() == wire.TBinary {
				var x string
				x, err = field.Value.GetString(), error(nil)
				v.WorkflowQuery = &x
				if err != nil {
					return err
				}

			}
		case 40:
			if field.Value.Type() == wire.TBinary {
				v.NextPageToken, err = field.Value.GetBinary(), error(nil)
				if err != nil {
					return err
				}

			}
		case 50:
			if field.Value.Type() == wire.TDouble {
				var x float64
				x, err = field.Value.GetDouble(), error(nil)
				v.SamplingRate = &x
				if err != nil {
					return err
				}

			}
		case 60:
			if field.Value.Type() == wire.TI32 {
				var x Mode
				x, err = _Mode_Read(field.Value)
				v.ShadowMode = &x
				if err != nil {
					return err
				}

			}
		case 70:
			if field.Value.Type() == wire.TStruct {
				v.ExitCondition, err = _ExitCondition_Read(field.Value)
				if err != nil {
					return err
				}

			}
		case 80:
			if field.Value.Type() == wire.TI32 {
				var x int32
				x, err = field.Value.GetI32(), error(nil)
				v.Concurrency = &x
				if err != nil {
					return err
				}

			}
		case 90:
			if field.Value.Type() == wire.TStruct {
				v.LastRunResult, err = _WorkflowResult_Read(field.Value)
				if err != nil {
					return err
				}

			}
		}
	}

	return nil
}

// String returns a readable string representation of a WorkflowParams
// struct.
func (v *WorkflowParams) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [9]string
	i := 0
	if v.Domain != nil {
		fields[i] = fmt.Sprintf("Domain: %v", *(v.Domain))
		i++
	}
	if v.TaskList != nil {
		fields[i] = fmt.Sprintf("TaskList: %v", *(v.TaskList))
		i++
	}
	if v.WorkflowQuery != nil {
		fields[i] = fmt.Sprintf("WorkflowQuery: %v", *(v.WorkflowQuery))
		i++
	}
	if v.NextPageToken != nil {
		fields[i] = fmt.Sprintf("NextPageToken: %v", v.NextPageToken)
		i++
	}
	if v.SamplingRate != nil {
		fields[i] = fmt.Sprintf("SamplingRate: %v", *(v.SamplingRate))
		i++
	}
	if v.ShadowMode != nil {
		fields[i] = fmt.Sprintf("ShadowMode: %v", *(v.ShadowMode))
		i++
	}
	if v.ExitCondition != nil {
		fields[i] = fmt.Sprintf("ExitCondition: %v", v.ExitCondition)
		i++
	}
	if v.Concurrency != nil {
		fields[i] = fmt.Sprintf("Concurrency: %v", *(v.Concurrency))
		i++
	}
	if v.LastRunResult != nil {
		fields[i] = fmt.Sprintf("LastRunResult: %v", v.LastRunResult)
		i++
	}

	return fmt.Sprintf("WorkflowParams{%v}", strings.Join(fields[:i], ", "))
}

func _Mode_EqualsPtr(lhs, rhs *Mode) bool {
	if lhs != nil && rhs != nil {

		x := *lhs
		y := *rhs
		return x.Equals(y)
	}
	return lhs == nil && rhs == nil
}

// Equals returns true if all the fields of this WorkflowParams match the
// provided WorkflowParams.
//
// This function performs a deep comparison.
func (v *WorkflowParams) Equals(rhs *WorkflowParams) bool {
	if !_String_EqualsPtr(v.Domain, rhs.Domain) {
		return false
	}
	if !_String_EqualsPtr(v.TaskList, rhs.TaskList) {
		return false
	}
	if !_String_EqualsPtr(v.WorkflowQuery, rhs.WorkflowQuery) {
		return false
	}
	if !((v.NextPageToken == nil && rhs.NextPageToken == nil) || (v.NextPageToken != nil && rhs.NextPageToken != nil && bytes.Equal(v.NextPageToken, rhs.NextPageToken))) {
		return false
	}
	if !_Double_EqualsPtr(v.SamplingRate, rhs.SamplingRate) {
		return false
	}
	if !_Mode_EqualsPtr(v.ShadowMode, rhs.ShadowMode) {
		return false
	}
	if !((v.ExitCondition == nil && rhs.ExitCondition == nil) || (v.ExitCondition != nil && rhs.ExitCondition != nil && v.ExitCondition.Equals(rhs.ExitCondition))) {
		return false
	}
	if !_I32_EqualsPtr(v.Concurrency, rhs.Concurrency) {
		return false
	}
	if !((v.LastRunResult == nil && rhs.LastRunResult == nil) || (v.LastRunResult != nil && rhs.LastRunResult != nil && v.LastRunResult.Equals(rhs.LastRunResult))) {
		return false
	}

	return true
}

// GetDomain returns the value of Domain if it is set or its
// zero value if it is unset.
func (v *WorkflowParams) GetDomain() (o string) {
	if v.Domain != nil {
		return *v.Domain
	}

	return
}

// GetTaskList returns the value of TaskList if it is set or its
// zero value if it is unset.
func (v *WorkflowParams) GetTaskList() (o string) {
	if v.TaskList != nil {
		return *v.TaskList
	}

	return
}

// GetWorkflowQuery returns the value of WorkflowQuery if it is set or its
// zero value if it is unset.
func (v *WorkflowParams) GetWorkflowQuery() (o string) {
	if v.WorkflowQuery != nil {
		return *v.WorkflowQuery
	}

	return
}

// GetSamplingRate returns the value of SamplingRate if it is set or its
// zero value if it is unset.
func (v *WorkflowParams) GetSamplingRate() (o float64) {
	if v.SamplingRate != nil {
		return *v.SamplingRate
	}

	return
}

// GetShadowMode returns the value of ShadowMode if it is set or its
// zero value if it is unset.
func (v *WorkflowParams) GetShadowMode() (o Mode) {
	if v.ShadowMode != nil {
		return *v.ShadowMode
	}

	return
}

// GetConcurrency returns the value of Concurrency if it is set or its
// zero value if it is unset.
func (v *WorkflowParams) GetConcurrency() (o int32) {
	if v.Concurrency != nil {
		return *v.Concurrency
	}

	return
}

type WorkflowResult struct {
	Succeeded *int32 `json:"succeeded,omitempty"`
	Skipped   *int32 `json:"skipped,omitempty"`
	Failed    *int32 `json:"failed,omitempty"`
}

// ToWire translates a WorkflowResult struct into a Thrift-level intermediate
// representation. This intermediate representation may be serialized
// into bytes using a ThriftRW protocol implementation.
//
// An error is returned if the struct or any of its fields failed to
// validate.
//
//   x, err := v.ToWire()
//   if err != nil {
//     return err
//   }
//
//   if err := binaryProtocol.Encode(x, writer); err != nil {
//     return err
//   }
func (v *WorkflowResult) ToWire() (wire.Value, error) {
	var (
		fields [3]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)

	if v.Succeeded != nil {
		w, err = wire.NewValueI32(*(v.Succeeded)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 10, Value: w}
		i++
	}
	if v.Skipped != nil {
		w, err = wire.NewValueI32(*(v.Skipped)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 20, Value: w}
		i++
	}
	if v.Failed != nil {
		w, err = wire.NewValueI32(*(v.Failed)), error(nil)
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 30, Value: w}
		i++
	}

	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

// FromWire deserializes a WorkflowResult struct from its Thrift-level
// representation. The Thrift-level representation may be obtained
// from a ThriftRW protocol implementation.
//
// An error is returned if we were unable to build a WorkflowResult struct
// from the provided intermediate representation.
//
//   x, err := binaryProtocol.Decode(reader, wire.TStruct)
//   if err != nil {
//     return nil, err
//   }
//
//   var v WorkflowResult
//   if err := v.FromWire(x); err != nil {
//     return nil, err
//   }
//   return &v, nil
func (v *WorkflowResult) FromWire(w wire.Value) error {
	var err error

	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 10:
			if field.Value.Type() == wire.TI32 {
				var x int32
				x, err = field.Value.GetI32(), error(nil)
				v.Succeeded = &x
				if err != nil {
					return err
				}

			}
		case 20:
			if field.Value.Type() == wire.TI32 {
				var x int32
				x, err = field.Value.GetI32(), error(nil)
				v.Skipped = &x
				if err != nil {
					return err
				}

			}
		case 30:
			if field.Value.Type() == wire.TI32 {
				var x int32
				x, err = field.Value.GetI32(), error(nil)
				v.Failed = &x
				if err != nil {
					return err
				}

			}
		}
	}

	return nil
}

// String returns a readable string representation of a WorkflowResult
// struct.
func (v *WorkflowResult) String() string {
	if v == nil {
		return "<nil>"
	}

	var fields [3]string
	i := 0
	if v.Succeeded != nil {
		fields[i] = fmt.Sprintf("Succeeded: %v", *(v.Succeeded))
		i++
	}
	if v.Skipped != nil {
		fields[i] = fmt.Sprintf("Skipped: %v", *(v.Skipped))
		i++
	}
	if v.Failed != nil {
		fields[i] = fmt.Sprintf("Failed: %v", *(v.Failed))
		i++
	}

	return fmt.Sprintf("WorkflowResult{%v}", strings.Join(fields[:i], ", "))
}

// Equals returns true if all the fields of this WorkflowResult match the
// provided WorkflowResult.
//
// This function performs a deep comparison.
func (v *WorkflowResult) Equals(rhs *WorkflowResult) bool {
	if !_I32_EqualsPtr(v.Succeeded, rhs.Succeeded) {
		return false
	}
	if !_I32_EqualsPtr(v.Skipped, rhs.Skipped) {
		return false
	}
	if !_I32_EqualsPtr(v.Failed, rhs.Failed) {
		return false
	}

	return true
}

// GetSucceeded returns the value of Succeeded if it is set or its
// zero value if it is unset.
func (v *WorkflowResult) GetSucceeded() (o int32) {
	if v.Succeeded != nil {
		return *v.Succeeded
	}

	return
}

// GetSkipped returns the value of Skipped if it is set or its
// zero value if it is unset.
func (v *WorkflowResult) GetSkipped() (o int32) {
	if v.Skipped != nil {
		return *v.Skipped
	}

	return
}

// GetFailed returns the value of Failed if it is set or its
// zero value if it is unset.
func (v *WorkflowResult) GetFailed() (o int32) {
	if v.Failed != nil {
		return *v.Failed
	}

	return
}
