// Code generated by thriftrw v1.8.0. DO NOT EDIT.
// @generated

package cadence

import "go.uber.org/thriftrw/version"

func init() {
	version.CheckCompatWithGeneratedCodeAt("1.8.0", "go.uber.org/cadence/.gen/go/cadence")
}
