package mocks

import "go.uber.org/cadence/internal/mocks"

type (
	// MockClient is an autogenerated mock type for the Client type.
	MockClient = mocks.Client

	// MockDomainClient is an autogenerated mock type for the DomainClient type
	MockDomainClient = mocks.DomainClient
)

// NewMockClient returns a new MockClient that can be used to mock Cadence client.
func NewMockClient() *MockClient {
	return &MockClient{}
}

// NewMockDomainClient returns a new MockDomainClient that can be used to mock Cadence DomainClient
func NewMockDomainClient() *MockDomainClient {
	return &MockDomainClient{}
}
