// Code generated by mockery v2.23.0. DO NOT EDIT.

// Copyright (c) 2017 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	internal "go.uber.org/cadence/internal"
)

// Registry is an autogenerated mock type for the Registry type
type Registry struct {
	mock.Mock
}

// RegisterActivity provides a mock function with given fields: a
func (_m *Registry) RegisterActivity(a interface{}) {
	_m.Called(a)
}

// RegisterActivityWithOptions provides a mock function with given fields: a, options
func (_m *Registry) RegisterActivityWithOptions(a interface{}, options internal.RegisterActivityOptions) {
	_m.Called(a, options)
}

// RegisterWorkflow provides a mock function with given fields: w
func (_m *Registry) RegisterWorkflow(w interface{}) {
	_m.Called(w)
}

// RegisterWorkflowWithOptions provides a mock function with given fields: w, options
func (_m *Registry) RegisterWorkflowWithOptions(w interface{}, options internal.RegisterWorkflowOptions) {
	_m.Called(w, options)
}

type mockConstructorTestingTNewRegistry interface {
	mock.TestingT
	Cleanup(func())
}

// NewRegistry creates a new instance of Registry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRegistry(t mockConstructorTestingTNewRegistry) *Registry {
	mock := &Registry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
