// Copyright (c) 2017-2021 Uber Technologies Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Code generated by mockery v2.16.0. DO NOT EDIT.

package internal

import mock "github.com/stretchr/testify/mock"

// MockWorkflowTaskHandler is an autogenerated mock type for the WorkflowTaskHandler type
type MockWorkflowTaskHandler struct {
	mock.Mock
}

type MockWorkflowTaskHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkflowTaskHandler) EXPECT() *MockWorkflowTaskHandler_Expecter {
	return &MockWorkflowTaskHandler_Expecter{mock: &_m.Mock}
}

// ProcessWorkflowTask provides a mock function with given fields: task, f
func (_m *MockWorkflowTaskHandler) ProcessWorkflowTask(task *workflowTask, f decisionHeartbeatFunc) (interface{}, error) {
	ret := _m.Called(task, f)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(*workflowTask, decisionHeartbeatFunc) interface{}); ok {
		r0 = rf(task, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*workflowTask, decisionHeartbeatFunc) error); ok {
		r1 = rf(task, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflowTaskHandler_ProcessWorkflowTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessWorkflowTask'
type MockWorkflowTaskHandler_ProcessWorkflowTask_Call struct {
	*mock.Call
}

// ProcessWorkflowTask is a helper method to define mock.On call
//   - task *workflowTask
//   - f decisionHeartbeatFunc
func (_e *MockWorkflowTaskHandler_Expecter) ProcessWorkflowTask(task interface{}, f interface{}) *MockWorkflowTaskHandler_ProcessWorkflowTask_Call {
	return &MockWorkflowTaskHandler_ProcessWorkflowTask_Call{Call: _e.mock.On("ProcessWorkflowTask", task, f)}
}

func (_c *MockWorkflowTaskHandler_ProcessWorkflowTask_Call) Run(run func(task *workflowTask, f decisionHeartbeatFunc)) *MockWorkflowTaskHandler_ProcessWorkflowTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*workflowTask), args[1].(decisionHeartbeatFunc))
	})
	return _c
}

func (_c *MockWorkflowTaskHandler_ProcessWorkflowTask_Call) Return(response interface{}, err error) *MockWorkflowTaskHandler_ProcessWorkflowTask_Call {
	_c.Call.Return(response, err)
	return _c
}

type mockConstructorTestingTNewMockWorkflowTaskHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockWorkflowTaskHandler creates a new instance of MockWorkflowTaskHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockWorkflowTaskHandler(t mockConstructorTestingTNewMockWorkflowTaskHandler) *MockWorkflowTaskHandler {
	mock := &MockWorkflowTaskHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
